version: '3.8'

networks:
  app-network:
    driver: bridge


services:

  postgres:
    image: postgres:15.4
    container_name: "${COMPOSE_PROJECT_NAME}-postgres"
    restart: always
    tty: true
    environment:
      POSTGRES_DB: ${PSQL_DATABASE}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_USER:  ${PSQL_USER}
      PGDATA: /var/lib/postgresql/data
    hostname: postgresDB
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "${HOST_MACHINE_PSQL_PORT}:${HOST_MACHINE_PSQL_PORT}"
    networks: 
      - app-network


  web:
    container_name: "${COMPOSE_PROJECT_NAME}-web"
    restart: unless-stopped
    build:
      context: ./php
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./php/php.ini:/usr/local/etc/php/conf.d/wp-php.ini
    depends_on:
      - postgres
    networks: 
      - app-network


  pgadmin4:
    image: dpage/pgadmin4:6.16
    container_name: "${COMPOSE_PROJECT_NAME}-pgadmin4"
    hostname: pgadmin4
    restart: unless-stopped
    ports:
      - "${HOST_MACHINE_PMA_PORT}:80"
    depends_on:
      - postgres
    links:
      - postgres  
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PSQL_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PSQL_PASSWORD}
        PGADMIN_LISTEN_PORT: ${HOST_MACHINE_UNSECURE_HOST_PORT}
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks: 
      - app-network
